name: Validar Script Shell

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Validar el script
        run: shellcheck hola.sh
